# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-13 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=254, unique=True)),
                ('last_name', models.CharField(max_length=254, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('contact_num', models.CharField(max_length=254)),
                ('company_name', models.CharField(max_length=254)),
                ('comp_reg_num', models.CharField(max_length=254, unique=True)),
                ('comp_addr', models.CharField(max_length=254, unique=True)),
                ('area_code', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
    ]
