# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-23 19:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='comp_addr',
            new_name='company_address',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='comp_name',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='comp_reg_num',
            new_name='company_reg_number',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='contact_num',
            new_name='contact_number',
        ),
    ]
