# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-09 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender_details', '0003_auto_20180408_2230'),
        ('user_account', '0002_auto_20171123_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='commodities',
            field=models.ManyToManyField(to='tender_details.category'),
        ),
    ]
