# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-09 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0003_customuser_commodities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='commodities',
        ),
    ]
