# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-12 12:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0006_customuser_commodities'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercategories',
            options={'verbose_name_plural': 'user categories'},
        ),
    ]
