# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-12 12:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0008_remove_customuser_commodities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercategories',
            name='catId',
        ),
        migrations.RemoveField(
            model_name='usercategories',
            name='userId',
        ),
        migrations.DeleteModel(
            name='userCategories',
        ),
    ]
