# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-13 19:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_account', '0010_auto_20180413_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=200)),
                ('companyRegNum', models.CharField(blank=True, max_length=30)),
                ('contactPerson', models.CharField(max_length=100)),
                ('contactNumber', models.CharField(max_length=20)),
                ('emailAddress', models.CharField(max_length=100)),
                ('companyAddress', models.TextField(blank=True, max_length=500)),
                ('billingContactPerson', models.CharField(max_length=100)),
                ('billingContactNumber', models.CharField(max_length=20)),
                ('billingEmailAddress', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='commodities',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='category',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
