# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-06 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyersName', models.CharField(max_length=100)),
                ('summary', models.CharField(max_length=300)),
                ('refNum', models.CharField(max_length=100)),
                ('issueDate', models.CharField(max_length=50)),
                ('closingDate', models.CharField(max_length=50)),
                ('siteInspection', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
