# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-08 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender_details', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('catCode', models.IntegerField(max_length=6, primary_key=True, serialize=False)),
                ('catDescription', models.CharField(max_length=100)),
            ],
        ),
    ]
