# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-08 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender_details', '0002_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='catCode',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
