# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-13 14:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tender_details', '0003_auto_20180408_2230'),
    ]

    operations = [
        migrations.DeleteModel(
            name='category',
        ),
    ]
