# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-13 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender_details', '0004_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catCode', models.IntegerField()),
                ('catDescription', models.CharField(max_length=100)),
            ],
        ),
    ]
